### ISSUE TITLE
Add a 'scrolling' option to get all pages

### ISSUE THREAD

**Issue by PascalTemel** [stawberri/danbooru-node#6]
As far as I know, the API currently returns a maximum of 200 posts per page. I think an option that recursively gets all the posts on all pages and merges them into a single array would be great.

**Comment by stawberri** [comment]
I don't want to add extra methods or parameters to this module that don't conform to Danbooru's official API, because I tried doing that in previous versions and it turned into a mess.

I think it would be better to implement the functionality you're suggesting in your own application, since it's likely you would want to customize the loop to suit your needs better.

You can do what you're suggesting like this:

```js
const Danbooru = require('danbooru')
const booru = new Danbooru()

async function getMultiplePages(tags) {
  let allPosts = []
  let page = 1
  const limit = 200

  while (true) {
    const posts = await booru.posts({ tags, limit, page })

    // Perform filtering actions here.

    allPosts = [...allPosts, ...posts]

    // If you want to notify the rest of your application of how this process
    // is coming along, you would do that here.

    // You might want to add an extra condition, such as
    //    allPosts.length > 2000
    // if you're working with large searches.
    if (!posts.length) break
    page++
  }

  return allPosts
}

getMultiplePages('nekopara').then(posts => {
  console.log(posts)
})
```

**Comment by PascalTemel** [comment]
Yeah I already implemented it before I opened the issue, just thought it would be nice to have it in the library, though I can understand your reasoning for not wanting to include it.
